INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000002, 1, 1000001, '17号泊位', '17号', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:51:17', 409000110, '2024-07-29 15:02:17', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000003, 2, 1000001, '18号南泊位', '18号南', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:53:44', 409000110, '2024-07-29 15:02:11', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000004, 3, 1000001, '18号北泊位', '18号北', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:54:31', 409000110, '2024-07-29 15:02:05', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000005, 4, 1000001, '19号东泊位', '19号东', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000115, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:55:31', 409000115, '2024-07-31 17:27:18', NULL, NULL, 113000047, NULL, NULL, NULL, 0);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000006, 5, 1000001, '19号西泊位', '19号西', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:55:55', 409000110, '2024-07-29 15:01:54', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000007, 6, 1000001, '20号东泊位', '20号东', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:56:17', 409000110, '2024-07-29 15:01:46', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000008, 7, 1000001, '20号西泊位', '20号西', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:56:45', 409000110, '2024-07-29 15:01:41', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000009, 1, 9000001, '17号泊位', '17号', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:51:17', 409000110, '2024-07-29 15:02:17', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000010, 2, 9000001, '18号南泊位', '18号南', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:53:44', 409000110, '2024-07-29 15:02:11', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000011, 3, 9000001, '18号北泊位', '18号北', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:54:31', 409000110, '2024-07-29 15:02:05', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000012, 4, 9000001, '19号东泊位', '19号东', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:55:31', 409000110, '2024-07-29 15:01:59', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000013, 5, 9000001, '19号西泊位', '19号西', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:55:55', 409000110, '2024-07-29 15:01:54', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000014, 6, 9000001, '20号东泊位', '20号东', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:56:17', 409000110, '2024-07-29 15:01:46', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);
INSERT INTO ope_operation_location
(id, ordinal, region_id, code, name, `level`, compulsory_inspect_flag, start_way, random_number, trigger_way, inspect_photo_flag, start_date, frequency_time, accident_photo_flag, violation_photo_flag, issue_photo_flag, photo_way, violation_principal_flag, accident_principal_flag, issue_principal_flag, status, principal, description, document_id, pic_document_id, tenant_id, sys_code, project_id, owner_id, owner_group_id, org_id, object_state, created_by, created_time, last_updated_by, last_updated_time, end_date, previous_time, form_id, fixed_previous_time, sign_in_flag, coordinate, sign_in_trigger_flag)
VALUES(16000015, 7, 9000001, '20号西泊位', '20号西', '一般', NULL, '自动开始', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '相机', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, 409000110, NULL, 27009123, 'enabled', 135000056, '2024-07-02 17:56:45', 409000110, '2024-07-29 15:01:41', NULL, NULL, 113000047, NULL, NULL, NULL, NULL);